### ISSUE TITLE
Unable to Validate Checksum

### ISSUE THREAD

**Issue by dslm4515** [firasuke/mussel#13]
```
.. Verifying binutils-2.40.tar.lz...
b3sum: skipping invalid checksum line
!. binutils-2.40.tar.lz is corrupted, redownloading...
```

mussel script gets stuck in a loop of downloading, attempting to check against checksum and then downloading again [same file]

I use the C implementation of the [b3sum](https://git.sr.ht/~mcf/b3sum) tool since most implementations are rust, like b3sum-ng

Perhaps add an option to use m5sum? Or perhaps, what is a good C/C++ implementation of b3sum?

**Comment by firasuke** [comment]
Are you still facing this issue?

**Comment by dslm4515** [comment]
Yeah. For now, I'm using the last commit before the switch to b3sum

**Comment by firasuke** [comment]
Meanwhile, can you provide a link to the version of `b3sum` you are using? It might have to do with how checks are performed (incorrect way of handling output, or output not identical between different versions/implementations), rather than the checksum being wrong.

**Comment by dslm4515** [comment]
I checked your script. Checksums are fine. Looks like the way the checksum is passed to b3sum may not be compatible. I'm not at my PC at the moment. I will check when I'm off work later today

**Comment by dslm4515** [comment]
I used this `b3sum` implementation: https://git.sr.ht/~mcf/b3sum
