### ISSUE TITLE
Got an "configure: error: cannot compute suffix of object files: cannot compile"

### ISSUE THREAD

**Issue by takusuman** [firasuke/mussel#17]
While I was building mussel via the Copacabana build system, I decided to look at the logs and saw that, at some point, the G.C.C. build broke:
![image](https://github.com/firasuke/mussel/assets/47103338/2bfa55da-9820-461d-960b-18032c7b940a)

The main script apparently exited on error, but Copacabana'\''s build script didn't stop there --- and I think that's my fault, so I will fix it as soon as possible.

![image](https://github.com/firasuke/mussel/assets/47103338/4e5282e3-7e46-4f3d-84ff-fe51eab75263)

I also noted some more errors, but they're on my front.

**Comment by takusuman** [comment]
Funnily enough, when I ran it again with ``dash`` instead of Slackware's ``/bin/sh`` (which is a damn symbolic link to GNU Broken-Again Shell), it built with no further trouble.

**Comment by firasuke** [comment]
> Funnily enough, when I ran it again with `dash` instead of Slackware's `/bin/sh` (which is a damn symbolic link to GNU Broken-Again Shell), it built with no further trouble.

If this is no longer an issue, then kindly close it.

**Comment by takusuman** [comment]
Sure.
I'm still testing here, if something new shows up I may reopen this with a comment.
For now, just a funky platform-specific bug on Slackware 15.

**Comment by firasuke** [comment]
> Sure. I'm still testing here, if something new shows up I may reopen this with a comment. For now, just a funky platform-specific bug on Slackware 15.

Sure thing. Feel free to reopen if the issue still persists.
