### ISSUE TITLE
lzip and zstd dependencies seem gratuitous

### ISSUE THREAD

**Issue by SpecLad** [firasuke/mussel#20]
As far as I can see, both of these are used to unpack a single package each (binutils and GMP, respectively). Both of those projects also publish `.xz` packages that are roughly of the same size. It would make it a bit easier to set up the build environment if you were to drop those dependencies and use the `.xz` packages instead.

**Comment by firasuke** [comment]
While I agree with your analogy for `lzip` and `xz`, I have to disagree with `zstd` as its used by GCC to provide a compression backend for LTO instead of plain `zlib`.

Feel free to submit a PR, and I'll hapilly review and merge it.

**Comment by firasuke** [comment]
> > I have to disagree with zstd as its used by GCC to provide a compression backend for LTO instead of plain zlib.
> 
> Okay, but for that you need the zstd development files, right? Not the command-line tool.

You're mostly correct, but not all host distributions provide split packages (e.g. Arch).
