### ISSUE TITLE
Maybe we could add a function to ``tail`` the log.txt file in case of error?

### ISSUE THREAD

**Issue by takusuman** [firasuke/mussel#33]
I've been trying to compile mussel for Copacabana in a virtual machine --- mostly because I don't want things to blew up in my host, so it's better to test it thoroughly before executing it in other hosts ---, and had problems with OOM and such, but it was extremely hard to figure it out because mussel would just quit and show nothing. That also applies for the check script not exiting with negative status if something is lacking in the system.

I think I can implement this until the next week, just wanted a second opinion (and someone willing to test it).

**Comment by firasuke** [comment]
That would be interesting indeed. We also need to bump the versions of software.

Then we can test both the change and the updates as well..

**Comment by takusuman** [comment]
> That would be interesting indeed.

Much obliged for the interest.

> Then we can test both the change and the updates as well..

I think this change can made debugging better later on.

**Comment by takusuman** [comment]
By the way, what do you think about #34? Do you wish to create a function that calls ``printf`` with an error message before ``tail``ing the log file or just use this as simple as it is?

**Comment by firasuke** [comment]
> > That would be interesting indeed.
> 
> Much obliged for the interest.
> 
> > Then we can test both the change and the updates as well..
> 
> I think this change can made debugging better later on.

Sure thing, I'll happily review the merge request once it's there.

**Comment by firasuke** [comment]
> By the way, what do you think about #34? Do you wish to create a function that calls `printf` with an error message before `tail`ing the log file or just use this as simple as it is?

The changes in #34 look fine by me. I prefer the simpler way.

**Comment by takusuman** [comment]
> I prefer the simpler way.

I mean, I understand, but I think this looks far more descriptive:

```console
S145% ./mussel "$(uname -m)" -l -o -k -p

+======================================================+
|  mussel - The fastest musl libc Toolchain Generator  |
+------------------------------------------------------+
|     Copyright (c) 2020-2024, Firas Khalil Khana      |
|    Distributed under the terms of the ISC License    |
+======================================================+

Target Architecture:            x86-64

Optional C++ Support:           yes
Optional Fortran Support:       no
Optional Linux Headers Support: yes
Optional OpenMP Support:        yes
Optional Parallel Support:      yes
Optional pkg-config Support:    yes
Optional Quadmath Support:      no


./mussel: line 698: return: can only `return' from a function or sourced script
!! Build failed!
!. Last lines of the log file (/usr/home/luiz/projetos/contribuições/mussel/log.txt):
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo

Start Time: Fri Sep 20 18:01:07 -03 2024
```

Than these:

```console
S145% ./mussel "$(uname -m)" -l -o -k -p

+======================================================+
|  mussel - The fastest musl libc Toolchain Generator  |
+------------------------------------------------------+
|     Copyright (c) 2020-2024, Firas Khalil Khana      |
|    Distributed under the terms of the ISC License    |
+======================================================+

Target Architecture:            x86-64

Optional C++ Support:           yes
Optional Fortran Support:       no
Optional Linux Headers Support: yes
Optional OpenMP Support:        yes
Optional Parallel Support:      yes
Optional pkg-config Support:    yes
Optional Quadmath Support:      no


./mussel: line 698: return: can only `return' from a function or sourced script
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo

Start Time: Fri Sep 20 18:01:07 -03 2024
```

I've added an ``return 1`` betwixt the code to force an error, so I could've test it --- of course I removed it before pushing.
This function for printing a message before printing the last 10 lines of the log file (which I shortened for pasting in this issue) was made here https://github.com/Projeto-Pindorama/mussel/commit/2d20cf1c81ca164d4341fd8f43862846ff700177. If you don't enjoy these, I can remove and it will go back to what it already was at https://github.com/Projeto-Pindorama/mussel/commit/74f1a17bb087d0cd630a00349a6e85a433fa814c.

**Comment by takusuman** [comment]
Well, in both situations, it's already done.
I will move from a draft to a proper pull request.

**Comment by firasuke** [comment]
> I mean, I understand, but I think this looks far more descriptive:
> 
> ```
> S145% ./mussel "$(uname -m)" -l -o -k -p
> 
> +======================================================+
> |  mussel - The fastest musl libc Toolchain Generator  |
> +------------------------------------------------------+
> |     Copyright (c) 2020-2024, Firas Khalil Khana      |
> |    Distributed under the terms of the ISC License    |
> +======================================================+
> 
> Target Architecture:            x86-64
> 
> Optional C++ Support:           yes
> Optional Fortran Support:       no
> Optional Linux Headers Support: yes
> Optional OpenMP Support:        yes
> Optional Parallel Support:      yes
> Optional pkg-config Support:    yes
> Optional Quadmath Support:      no
> 
> 
> ./mussel: line 698: return: can only `return' from a function or sourced script
> !! Build failed!
> !. Last lines of the log file (/usr/home/luiz/projetos/contribuições/mussel/log.txt):
> BUG_REPORT_URL="https://bugs.artixlinux.org/"
> PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
> LOGO=artixlinux-logo
> 
> Start Time: Fri Sep 20 18:01:07 -03 2024
> ```

Now that you mention it, it does look better.

> I will move from a draft to a proper pull request.

Sure thing, take your time.

**Comment by takusuman** [comment]
Just perceived that this code won't work on dash just because ``trap`` on POSIX faithful implementations doesn't have access to variables nor functions declared on the code; in other words, it seems like it is evaluated at the time it is declared and not when it has to be called.
I honestly question why the POSIX standard, even though it's basically a "bougiefied" Bourne shell with some proprietary UNIX vendors and KornShell 88 extensions, still being so suffering-worthy sometimes.
Anyway, for now, a fix would be to call ``/bin/ksh93`` --- haven't tested with ``ksh88``/OpenBSD's ``pdksh``, though --- or ``/bin/bash`` until I can refactor these and get some way out that doesn't make the code look like a pile or mere hacks.
Pardon for the hassle, but I think this feature was more needed than compatibility, at least for now.
