### ISSUE TITLE
Refactoring error made linux generated headers no longer generated

### ISSUE THREAD

**Issue by themaks** [firasuke/mussel#38]
> Hello,
> 
> You introduced a bug with this refactor: the generated headers are no longer generated, I think you at least need to call `make headers` before copying `.h` files
> 
> Cheers 

 _Originally posted by @themaks in [a81c020](https://github.com/firasuke/mussel/commit/a81c020c983f2f30390507407abf2059d6dfb491#r149500647)_

**Comment by firasuke** [comment]
Thanks for catching that, should be fixed now.
